//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reservation3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int id { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string date { get; set; }
        public string time { get; set; }
        public Nullable<int> prix { get; set; }
        public Nullable<int> nombre_de_place { get; set; }
        public string date_de_retour { get; set; }
        public string time_de_retour { get; set; }
        public string way { get; set; }
    }
}
